### ISSUE TITLE
Run wireguard_exporter as daemon

### ISSUE THREAD

**Issue by detzen** [kbknapp/wireguard_exporter#15]
Currently I use the wireguard_exporter binary v.0.3.0 on Alpine 3.19 to export metrics from the wireguard service running locally on the machine. Unfortunately, there is no -d flag to start the exporter as daemon. It would also be nice to specify a logfile instead of loging to stout only. Are there plans to implement such flags or what's the prefered way to run the exporter in the background?
Regards,
Alex

**Comment by Friedjof** [comment]
To set up the `wireguard_exporter` as a Systemd service, follow these steps:

1. **Create the Service File**:

   ```bash
   sudo nano /etc/systemd/system/wireguard_exporter.service
   ```

2. **Add the Following Content**:

   ```ini
   [Unit]
   Description=WireGuard Exporter for Prometheus
   Wants=network-online.target
   After=network-online.target

   [Service]
   User=root
   ExecStart=/usr/local/bin/wireguard_exporter
   Restart=on-failure

   [Install]
   WantedBy=multi-user.target
   ```

3. **Enable and Start the Service**:

   ```bash
   sudo systemctl daemon-reload
   sudo systemctl start wireguard_exporter
   sudo systemctl enable wireguard_exporter
   ```

4. **Check the Status**:

   ```bash
   sudo systemctl status wireguard_exporter
   ```

The exporter should now run as a background service.

**Comment by detzen** [comment]
Thanks for your quick reply. I'll close the issue now.
